version: 2

jobs:
  build:
    working_directory: ~/forms
    docker:
      - image: circleci/node:10.12.0
        environment:
          CI: 1
    steps:
      - checkout
      - run:
          name: Upgrade yarn
          command: sudo npm install -g yarn
      - run:
          name: Installing javascript dependencies
          command: yarn install --cache-folder ~/.yarn-cache
      - run:
          name: Linting the source code
          command: yarn lint
      - run:
          name: Typechecking the source code
          command: yarn typecheck
      - run:
          name: Testing the source code
          command: yarn test:ci

workflows:
  version: 2
  test:
    jobs:
      - build
