version: 2

jobs:
  build:
    working_directory: ~/forms
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run:
          name: Installing javascript dependencies
          command: yarn install --cache-folder ~/.yarn-cache
      - run:
          name: Linting the source code
          command: yarn lint
      - run:
          name: Typechecking the source code
          command: yarn typecheck:all
      - run:
          name: Testing the source code
          command: yarn test:ci
      - run:
          name: Bundlesize
          command: |
            yarn build
            yarn bundlesize

workflows:
  version: 2
  test:
    jobs:
      - build
